import{a as b,S,i as d}from"./assets/vendor-BJ7ir7Fo.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const w="https://pixabay.com/api/",q="54246906-f81d1c2d6c5eb45f9ea82e11c";async function v(t,r){return(await b.get(w,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new S(".gallery a");function M(t){const r=t.map(({webformatURL:n,largeImageURL:a,tags:e,likes:o,views:i,comments:p,downloads:L})=>`<li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" />
        </a>
        <ul class="image-info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${i}</li>
          <li><b>Comments:</b> ${p}</li>
          <li><b>Downloads:</b> ${L}</li>
        </ul>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),B.refresh()}function $(){m.innerHTML=""}function O(){h.classList.remove("is-hidden")}function P(){h.classList.add("is-hidden")}function x(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const u=document.querySelector(".form"),E=document.querySelector(".load-more");let s=1,l="",f=0;async function g(){try{O();const t=await v(l,s),r=t.hits;if(s===1&&r.length===0){c(),d.error({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}M(r),f=Math.ceil(t.totalHits/15),s>=f?(c(),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):x(),s+=1,A()}catch(t){console.error(t)}finally{P()}}u.addEventListener("submit",t=>{t.preventDefault(),l=t.target.elements["search-text"].value.trim(),l&&(s=1,$(),c(),g(),u.reset())});E.addEventListener("click",g);function A(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
